### ISSUE TITLE
FLIR camera settings don't work as expected

### ISSUE THREAD

**Issue by olinesn** [ksseverson57/campy#18]
Hello,

I'm using FLIR cameras, and while I can easily control a camera's settings from the Spinview GUI (Gain, Exposure duration), the options in my config file don't seem to overwrite them.

Rather, it seems to not matter what my config file settings are. Only the settings that I choose in Spinview seem to influence the output.

> # This beginner-level config uses the CPU (gpuID: -1) to compress video
> # using ffmpeg's X264 codec
> 
> # Recording parameters
> videoFolder: "D:\\CAMPY\\campy_testA"
> videoFilename: "Test_GUI01ms_Config01ms.mp4"
> frameRate: 60
> recTimeInSec: 20
> ffmpegLogLevel: "info"               # "quiet", "warning", "info"
> 
> 
> # Camera parameters
> numCams: 1
> cameraMake: "flir"
> frameWidth: 1936
> frameHeight: 1464
> 
> # Flir settings
> cameraTrigger: "Line3"
> bufferSize: 100
> cameraExposureTimeInUs: 1000
> cameraGain: 1
> disableGamma: False
> 
> # Compression parameters
> pixelFormatInput: "gray"
> pixelFormatOutput: "rgb0"
> gpuID: 0                          
> gpuMake: "nvidia"                     # "nvidia", "amd", "intel"                  
> codec: "h265"                         # "h264", "h265", or user-defined video codec
> quality: 21                           # 0-55
> preset: "fast"                        # How much effort should be put into reducing the file size?
> 
> # Display parameters
> displayFrameRate: 10
> 
> startArduino: True 
> digitalPins: [6] # e.g. [0,1,2]
> serialPort: "COM5" # e.g. "COM3" or "/dev/ttyACM0"

Is it possible that I'm doing something wrong, or is this possible a bug?

Thanks!
Stefan

<img width="495" alt="image" src="https://github.com/ksseverson57/campy/assets/69451171/9cd62d98-6ee5-475d-bbde-4d578b078c4c">

**Comment by ksseverson57** [comment]
factory reset has been added to the camera initialization to fix this issue
